[package]
name = "network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
laminar = "0.5.0"
crossbeam-channel = "0.5.2"
strum = "0.23"
strum_macros = "0.23"
game = { path = "../game" }
